### ISSUE TITLE
Restrict Access to MySQL / REDIS

### ISSUE THREAD

**Issue by MaximeBaudette** [GRIDAPPSD/gridappsd-forum#112]
The cybersecurity team, where I work (LBNL), flagged my computer for exposing both MYSQL and REDIS databases to the internet. 
Is there a flag / command to execute the database containers in "local" mode where they only listen to 127.0.0.1 and dump traffic coming from somewhere else ?

**Comment by MaximeBaudette** [comment]
I solved it by modifying the docker-compose by adding a more specific port binding restricting it to 127.0.0.1


```
redis:
    image: redis:3.2.11-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

    volumes:
      - ./gridappsd/redis/data:/data
    entrypoint: redis-server --appendonly yes

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
```
